### ISSUE TITLE
authentication "cookies.txt" process

### ISSUE THREAD

**Issue by drmmy** [knowbee/llvd#40]
Hello,

I am completely new to Python. Would it be possible to explain the steps for creating & saving the `cookies.txt` file? I'm using Chrome on Mac OS. 

This is what I tried:

1. [opened **TextEdit** > typed in values for `JSESSION=` & `li_at=` (on 1st line & 2nd line of text) > renamed the plain text file as `cookies.txt` > then, saved the `cookies.txt` to my **Desktop**].

2. [opened **Terminal App** > entered `llvd -c "photoshop-for-designers-working-with-shapes" -ca`

3. `Do you want to login with cookies? [y/N]: y`

4. Error Msg (in red): `cookies.txt must not be empty`

Note: I also tried to run the code by entering my LinkedIn Learning School Organization credentials. This allowed for a few of the course videos to download—the rest of the videos showed a downloading error msg: `This video is locked, you probably need a premium account`.

Any feedback would be appreciated, thank you! & thank you for creating this! =)

**Comment by knowbee** [comment]
This is simply caused by the fact that the account provided by the your school organization is not premium. Some courses on linkedin learning platform requires you to  have a premium account.

Note: make sure you have followed all the instructions detailed here while using cookie based authentication ==> https://github.com/knowbee/llvd#cookie-based-authentication
