### ISSUE TITLE
"This video is locked, you probably need a premium account"

### ISSUE THREAD

**Issue by theazlan89** [knowbee/llvd#93]
Hi, My account is premium and attached with organization. How to link this?

**Comment by mirza-asad** [comment]
waiting for any update plz,  about this issue video locked issue?

**Comment by knowbee** [comment]
Is this happening on multiple courses, or is it only happening on one?

**Comment by PhilipMathieu** [comment]
I'm also experiencing this issue. My organization uses SSO for authentication. Even though it is linked to a valid personal account, the personal email and password alone are not sufficient to access the course materials with `llvd`.

**Comment by ordnl** [comment]
The request `https://www.linkedin.com/learning-api/detailedCourses`, does not always have the `url` key. This was fixed for me by adding the `li_ep_auth_context` to the `cookies.txt` file.

I think a better fallback should be written by extracting the `url` from the actual video page instead of making a call to `learning-api/detailedCourses`, closer to how the client actual does it.

**Comment by knowbee** [comment]
@ordnl Do you mind contributing to the project and make the suggested changes ?
